version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-tasks-api
    ports:
      - "8080:8080"
    network_mode: host
    command: ["/app/main"]
